#===============================
#  Configuracion de ejemplo (para @Value / SpEL)
#===============================
app.sistema.nombre=Sistema de Gestion de Items
app.item.valor-maximo=1000
app.item.alerta-habilitada=true
